apiVersion: v1
kind: Pod
metadata:
  name: net-tester
  namespace: default
  labels:
    run: kubeweb-tester
spec:
  containers:
  - image: drlee001/net-tester
    imagePullPolicy: IfNotPresent
    name: net-tester
  restartPolicy: Always
